spring:
  datasource:
   # username: root
   # password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
   # url: jdbc:mysql://106.13.43.152:3306/mp?useUnicode=true&useSSL=true&serverTimezone=UTC
    url: jdbc:oracle:thin:@106.13.43.152:1521:helowin
    username: test
    password: test

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml
logging:
  level:
    root: warn
    com.itzhuo.mapper: trace
  pattern:
    console: '%p%m%n'