spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.13.43.152:3306/mp?useUnicode=true&useSSL=true&serverTimezone=UTC
